### ISSUE TITLE
Update python dependency for arm32.v7 image.

### ISSUE THREAD

**Issue by FluxReality** [Azure/cookiecutter-azure-iot-edge-module#19]
For version 1.4.3 of **azure-iothub-device-client** python package, it's recommended that  version of boost is >= 1.58. (Se [pypi](https://pypi.org/project/azure-iothub-device-client/) description).

**resin/raspberrypi3-python** Is based of jessie images from resin, where the highest available **libboost-python** is 1.55.

This causes all sorts of problems running on Raspberry Pi. The docker file should be updated to support the latest release of azure-iothub-device-client.

**Comment by formulahendry** [comment]
@FluxReality , the updated template is merged into our `develop` branch, you could run `cookiecutter https://github.com/Azure/cookiecutter-azure-iot-edge-module --checkout develop` to have a try.

**Comment by formulahendry** [comment]
Hi @FluxReality , our new python cookiecutter package is released now. For arm32v7 image, it is using libboost-python1.62.0 now. You could create a new Python Module with our VS Code IoT Edge extension.
