### ISSUE TITLE
Add Device Twin stub to cookiecutter template

### ISSUE THREAD

**Issue by WilliamBerryiii** [Azure/cookiecutter-azure-iot-edge-module#24]
It would be helpful to add a device twin function set to the cookie cutter template to align to the implementation in the .Net templates.

**Comment by blackchoey** [comment]
Hi @WilliamBerryiii Thanks for the suggestion. The purpose of this template is to help people quickly create a new Python module. The sample code in the template is very basic to help people get started. It would be better to follow the Azure IoT Edge [tutorials](https://docs.microsoft.com/en-us/azure/iot-edge/) to implement more functions.
In the meanwhile, the [dotnet template](https://github.com/Azure/dotnet-template-azure-iot-edge-module/blob/master/content/dotnet-template-azure-iot-edge-module/CSharp/Program.cs) do not have device twin related function. Please let us know if you're referring another template. Thank you very much.

**Comment by konichi3** [comment]
@marianan pls close this
