### ISSUE TITLE
Dockerfile.arm32v7 references deprecated resin repo on Dockerhub

### ISSUE THREAD

**Issue by toolboc** [Azure/cookiecutter-azure-iot-edge-module#26]
# Description of the issue:
Dockerfile.arm32v7 supplied by generator for IoT Edge python modules is referencing a deprecated base image provided by [resin](https://hub.docker.com/u/resin/) on Dockerhub.  Theis should be updated to support newer images provided by [balenalib](https://hub.docker.com/u/balenalib/).

# Code sample exhibiting the issue:
[Dockerfile.arm32v7](https://github.com/Azure/cookiecutter-azure-iot-edge-module/blob/develop/%7B%7Bcookiecutter.module_name%7D%7D/Dockerfile.arm32v7#L1)

> FROM resin/raspberrypi3-debian:stretch

![image](https://user-images.githubusercontent.com/2018336/59620937-b6cf4380-90f3-11e9-9e5f-28b0fb1b0a83.png)

This image reference should be updated to:
`balenalib/raspberrypi3-debian:stretch`

**Comment by blackchoey** [comment]
Thanks for your contribution. The template now uses the official python base image. So I'm going to close this issue.
