### ISSUE TITLE
 500 Internal Server Error when docker push localhost image for windows-amd64.debug

### ISSUE THREAD

**Issue by czgtest** [Azure/cookiecutter-azure-iot-edge-module#32]
repro on : arm64-preview

1.set python version in VSCode settings
"azure-iot-edge.version.pythonmodule": "arm64-preview"
2.create python module
3.build and Push python module 
received unexpected HTTP status: 500 Internal Server Error when  push localhost:5000/samplemodulepython:0.0.1-windows-amd64.debug

does windows docker image support localhost? 

![image](https://user-images.githubusercontent.com/35018765/66695060-04993880-ecef-11e9-8f50-0b12c2ef7a46.png)

**Comment by czgtest** [comment]
python module can't be connected when run solution in simulator 
![image](https://user-images.githubusercontent.com/35018765/66695257-ff89b880-ecf1-11e9-8df7-f065c61e932a.png)

**Comment by blackchoey** [comment]
It's expected. Windows container does not have local registry.
